package project.client.pdf;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import projects.serveur.entites.Project;

public class CreatePdf {
	
	private Project p ;
	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
    Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
	Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
    Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
    Font.BOLD);
    Document document = new Document();
	
    public CreatePdf(Project p)
    {
    	this.p=p;
    }

	public  void writePdf() {
		try {	
			
	   	
	       OutputStream file = new FileOutputStream(new File("C:\\Users\\Hichem\\Desktop\\pdf\\"+p.getName()+".pdf"));
		   PdfWriter.getInstance(document, file);
		   document.open();
		   addTitlePage();
		   document.close();
		   file.close();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	  private  void addTitlePage()
	 throws DocumentException {
	 Paragraph preface = new Paragraph();		   	
     preface.add(new Paragraph("Rapport of project "+p.getName(), catFont)); 
     addEmptyLine(preface, 1);
     preface.add(new Paragraph("Report generated by: Hichem Nasri, " + new Date(), 
     smallBold));
     addEmptyLine(preface, 1);
	 preface.add(new Paragraph("This document describes details of project ",
	 smallBold));
	 
	 addEmptyLine(preface, 8);
     preface.add(new Paragraph("This document describe a project for archieved details.",
      redFont));
	  document.add(preface);
		    
		   // document.newPage();
		  }
	  private static void addEmptyLine(Paragraph paragraph, int number) {
		    for (int i = 0; i < number; i++) {
		      paragraph.add(new Paragraph(" "));
		    }
		  }

}
