package project.client.pdf;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import projects.serveur.entites.Project;

public class CreatePdf {
	
	private Project p ;
	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
    Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
	Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
    Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
    Font.BOLD);
    Document document = new Document();
	
    public CreatePdf(Project p)
    {
    	this.p=p;
    }

	public  void writePdf() {
		try {	
			
	   	
	       OutputStream file = new FileOutputStream(new File("C:\\Users\\Hichem\\Desktop\\pdf\\"+p.getName()+".pdf"));
		   PdfWriter.getInstance(document, file);
		   document.open();
		   addTitlePage();
		   document.close();
		   file.close();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	  private  void addTitlePage()
	 throws DocumentException {
	 Paragraph preface = new Paragraph();
	 addEmptyLine(preface, 6);
     preface.add(new Paragraph("Rapport of project "+p.getName(), catFont)); 
     addEmptyLine(preface, 1);
     preface.add(new Paragraph("Report generated by: Hichem Nasri, " + new Date(), 
     smallBold));
     addEmptyLine(preface, 1);
	 preface.add(new Paragraph("Name of project : "+p.getName(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Title of project : "+p.getTitle(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Duration of project : "+p.getDuration(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Location of project : "+p.getLocation(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Presentation : " +p.getShort_presentation(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Turget of project : " +p.getTurget_funding(),
	smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Date publish : "+p.getDate_publish(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Category: "+p.getCategory().getName_category(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Creator name: "+p.getCreator().getFirstname()+" "+p.getCreator().getLastname(),
	 smallBold));
	 addEmptyLine(preface, 2);
	 preface.add(new Paragraph("Creator email: " +p.getCreator().getEmail(),
	 smallBold));
	 Image image1 = null;
	try {
		image1 = Image.getInstance("C:\\Users\\Hichem\\workspace\\project.client\\src\\main\\resources\\Pictures\\smartdev.png");
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
     document.add(image1);
	
	 document.add(preface);	    
	 document.newPage();
		  }
	  private static void addEmptyLine(Paragraph paragraph, int number) {
		    for (int i = 0; i < number; i++) {
		      paragraph.add(new Paragraph(" "));
		    }
		  }

}
